[package]
name = "nosana-jobs"
version = "0.1.0"
description = "Nosana Jobs for decentralized CI/CD and computation."
edition = "2021"
homepage = "https://nosana.io/"
authors = ["nosana"]
license = "MIT"
keywords = ["solana", "nosana", "cicd", "jobs", "anchor"]

[lib]
crate-type = ["cdylib", "lib"]
name = "nosana_jobs"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-spl = { version = "0.27.0" }
anchor-lang = { version = "0.27.0" }
mpl-token-metadata = { version = "1.10.0", features = [ "no-entrypoint" ] }
nosana-staking = { path = "../nosana-staking", features = ["cpi"] }
nosana-rewards = { path = "../nosana-rewards", features = ["cpi"] }
nosana-common = { path = "../../common" }
