[package]
name = "nosana-jobs"
version = "0.1.0"
description = "Nosana Jobs for decentralized CI/CD and computation."
edition = "2021"
homepage = "https://nosana.io/"
authors = ["nosana"]
license = "MIT"
keywords = ["solana", "nosana", "cicd", "jobs", "anchor"]

[lib]
crate-type = ["cdylib", "lib"]
name = "nosana_jobs"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
mpl-token-metadata =  "1.3.4"
nosana-staking = { path = "../nosana-staking", features = ["cpi"] }
nosana-common = { path = "../../common" }
