image: projectserum/build:v0.22.0

stages:
  - build
  - test
  - deploy
  - post

variables:
  TARGET: target/deploy/nosana_jobs.so
  SOLANA_PROGRAM_ID: nosJwntQe4eEnFC2mCsY9J15qw7kRQCDqcjcPj6aPbR

.anchor:
  before_script:
    - echo $SOLANA_WALLET > ~/.config/solana/id.json
  after_script:
    - rm ~/.config/solana/id.json

build:
  extends: .anchor
  stage: test
  script:
    - yarn install
    - anchor test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - $TARGET

.deploy:
  extends: .anchor
  stage: deploy
  script:
    - anchor upgrade $TARGET \
        --program-id $SOLANA_PROGRAM_ID \
        --provider.cluster $CLUSTER \
        --provider.wallet ~/.config/solana/id.json

deploy devnet:
  extends: .deploy
  variables:
    CLUSTER: devnet
  rules:
    - if: $CI_MERGE_REQUEST_ID

deploy testnet:
  extends: .deploy
  variables:
    CLUSTER: testnet
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy mainnet:
  extends: .deploy
  variables:
    CLUSTER: mainnet
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release:
  image: registry.gitlab.com/nosana-ci/tools/containers/semver
  script: release.sh
  stage: post
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
