include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: anchor.yaml

variables:
  TARGET: target/deploy/nosana_jobs.so
  IDL_PATH: target/idl/nosana_jobs.json
  PROGRAM_ID: nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM
  BUILD_SCRIPT: scripts/build.sh
