include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: anchor.yaml

variables:
  TARGET: target/deploy/nosana_jobs.so
  PROGRAM_ID: nosJwntQe4eEnFC2mCsY9J15qw7kRQCDqcjcPj6aPbR
  BUILD_SCRIPT: scripts/build.sh

build:
  extends: build
  script:
    - sed -i 's/#default/default/' programs/nosana_jobs/Cargo.toml
    - anchor build
