image: projectserum/build:v0.22.0

stages:
  - build
  - test
  - deploy
  - post

variables:
  SOLANA_IDS_PATH: ~/.config/solana/

before_script:
  - echo $SOLANA_WALLET > $SOLANA_IDS_PATH/id.json

build:
  stage: build
  script:
    - anchor build
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - target

test:
  stage: test
  script:
    - yarn install
    - anchor test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  script:
    - echo $SOLANA_PROGRAM_ID > $SOLANA_IDS_PATH/pid.json
    - solana -u devnet program deploy --program-id $SOLANA_IDS_PATH/pid.json target/deploy/jobs.so
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release:
  image: registry.gitlab.com/nosana-ci/tools/containers/semver
  script: release.sh
  stage: post
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
