image: projectserum/build:v0.22.0

stages:
  - build
  - test
  - deploy
  - post

variables:
  TARGET: target/deploy/nosana_jobs.so
  PATH_WALLET: ~/.config/solana/id.json
  PATH_PROGRAM_ID: ~/.config/solana/pid.json

.anchor:
  before_script:
    - echo $SOLANA_WALLET > $PATH_WALLET
    - echo $SOLANA_PROGRAM_ID > $PATH_PROGRAM_ID
  after_script:
    - rm  ~/.config/solana/*.json

build:
  extends: .anchor
  stage: test
  script:
    - yarn install
    - anchor test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - $TARGET

.deploy:
  extends: .anchor
  stage: deploy
  script:
    - solanaprogram deploy -u $DEPLOY_NET -k $PATH_WALLET $TARGET $PATH_PROGRAM_ID

deploy devnet:
  extends: .deploy
  variables:
    DEPLOY_NET: devnet
  rules:
    - if: $CI_MERGE_REQUEST_ID

deploy testnet:
  extends: .deploy
  variables:
    DEPLOY_NET: testnet
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy mainnet:
  extends: .deploy
  variables:
    DEPLOY_NET: mainnet
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release:
  image: registry.gitlab.com/nosana-ci/tools/containers/semver
  script: release.sh
  stage: post
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
