include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: anchor.yml

variables:
  PREPARE_SCRIPT: scripts/prepare.sh

.parallel:
  parallel:
    matrix:
      - PROGRAM_NAME: nosana_staking
        PROGRAM_ID: nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE
      - PROGRAM_NAME: nosana_rewards
        PROGRAM_ID: nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp.json
      - PROGRAM_NAME: nosana_jobs
        PROGRAM_ID: nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM
