image: projectserum/build:v0.20.1

stages:
  - build
  - test
  - deploy
  - post

build:
  stage: test
  script:
    - yarn install
    - anchor build
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - target

test:
  stage: test
  script:
    - yarn install
    - anchor test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - target

release:
  image: registry.gitlab.com/nosana-ci/tools/containers/semver
  script: release.sh
  stage: post
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
