include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: anchor.yml

variables:
  PREPARE_SCRIPT: scripts/prepare.sh

.parallel:
  parallel:
    matrix:
      - PROGRAM_NAME: nosana_jobs
        PROGRAM_ID: nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM
      - PROGRAM_NAME: nosana_pools
        PROGRAM_ID: nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD
      - PROGRAM_NAME: nosana_rewards
        PROGRAM_ID: nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp

scenario:
  extends: .wallet
  stage: test
  parallel:
    matrix:
      - TEST_SCENARIO: rewards
      - TEST_SCENARIO: all
  script:
    - npm ci
    - anchor test
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  cache:
    key: target
    paths:
      - target/
