anchor_version = "0.19.0"

[programs.localnet]
jobs = "testzMFv8LK3mjsJdakJ2LQPGpWPPQhZ3QiriRWzJUM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js --exit"
