anchor_version = "0.25.0"

[workspace]
members = [
    "programs/nosana-pools",
    "programs/nosana-jobs",
    "programs/nosana-staking",
    "programs/nosana-rewards",
]

[features]
seeds = false
skip-lint = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "npx ts-mocha -t 1000000 tests/tests.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/programs/mpl_token_metadata.so"

[programs.localnet]
nosana_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
nosana_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"
nosana_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
nosana_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"

[programs.devnet]
nosana_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
nosana_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"
nosana_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
nosana_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"

[programs.testnet]
nosana_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
nosana_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"
nosana_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
nosana_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"

[programs.mainnet]
nosana_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
nosana_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"
nosana_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
nosana_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"