anchor_version = "0.27.0"

[workspace]
members = [
#    "common",
    "programs/nosana-jobs",
    "programs/nosana-pools",
    "programs/nosana-rewards",
    "programs/nosana-staking",
]

[features]
seeds = false
skip-lint = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "npm run test"

[test]
startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/programs/mpl_token_metadata.so"

[programs.localnet]
nosana_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
nosana_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"
nosana_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
nosana_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"

[programs.devnet]
nosana_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
nosana_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"
nosana_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
nosana_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"

[programs.testnet]
nosana_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
nosana_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"
nosana_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
nosana_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"

[programs.mainnet]
nosana_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
nosana_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"
nosana_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
nosana_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"
