anchor_version = '0.24.2'

[programs.localnet]
nosana_common = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
nosana_jobs = 'nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM'
nosana_staking = 'nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE'
nosana_rewards = 'nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp'

[programs.devnet]
nosana_common = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
nosana_jobs = 'nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM'
nosana_staking = 'nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE'
nosana_rewards = 'nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp'


[programs.testnet]
nosana_common = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
nosana_jobs = 'nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM'
nosana_staking = 'nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE'
nosana_rewards = 'nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp'

[programs.mainnet]
nosana_common = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
nosana_jobs = 'nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM'
nosana_staking = 'nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE'
nosana_rewards = 'nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp'

[[test.genesis]]
address = 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'
program = 'tests/mpl_token_metadata.so'

[registry]
url = 'https://anchor.projectserum.com'

[provider]
cluster = 'localnet'
wallet = '~/.config/solana/id.json'

[scripts]
test = 'npx ts-mocha  -t 1000000 tests/tests-rewards.ts'
testall = 'npx ts-mocha --require mocha-suppress-logs -t 1000000 tests/**/*.ts'
