anchor_version = "0.19.0"

[programs.localnet]
jobs = "nosJwntQe4eEnFC2mCsY9J15qw7kRQCDqcjcPj6aPbR"

[programs.devnet]
jobs = "nosJwntQe4eEnFC2mCsY9J15qw7kRQCDqcjcPj6aPbR"

[programs.testnet]
jobs = "nosJwntQe4eEnFC2mCsY9J15qw7kRQCDqcjcPj6aPbR"

[programs.mainnet]
jobs = "nosJwntQe4eEnFC2mCsY9J15qw7kRQCDqcjcPj6aPbR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js --exit"
