[package]
name = "nosana-rewards"
version = "0.1.0"
description = "Reflection rewards for Nosana"
edition = "2021"
homepage = "https://nosana.io/"
authors = ["nosana"]
license = "MIT"
keywords = ["solana", "nosana", "cicd", "staking", "anchor"]

[lib]
crate-type = ["cdylib", "lib"]
name = "nosana_rewards"

[features]
#default = ["mainnet"]
mainnet = []
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"
nosana-staking = { path = "../nosana-staking", features = ["cpi"]}
nosana-common = { path = "../nosana-common", features = ["cpi"]}