[package]
name = "nosana_jobs"
version = "0.1.0"
description = "Created with Anchor"
authors = ["nosana"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "nosana_jobs"

[features]
#default = ["mainnet"]
mainnet = []

[dependencies]
anchor-lang = "0.22.0"
anchor-spl = "0.22.0"
